version: '3.9'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  authoring-editor-db:
    image: '${DBIMAGE}'
    restart: 'always'
    ports:
      - '${DBPORT}:${DBPORT}'
    environment:
      POSTGRES_PASSWORD: '${DBPASS}'
      POSTGRES_USER: '${DBUSER}'
  authoring-editor-server:
    build:
      context: ../
      dockerfile: containers/development.dockerfile
    ports:
      - '${SRPORT}:${SRPORT}'
    volumes:
      - ../packages/editor/package.json:/usr/authoring/packages/editor/package.json
      - ../packages/editor/src/main:/usr/authoring/packages/editor/src/main
      - ../packages/editor/src/server:/usr/authoring/packages/editor/src/server
      - ../packages/editor/src/app:/usr/authoring/packages/editor/src/app
      - ../packages/content-block-editor-react/dist:/usr/authoring/packages/content-block-editor-react/dist