version: '3'
services:
  server:
    build:
      context: ../
      dockerfile: containers/web.dockerfile
    ports:
      - '${SRPORT}:${SRPORT}'
  db:
    image: '${DBIMAGE}'
    restart: 'always'
    ports:
      - '${DBPORT}:${DBPORT}'
    environment:
      POSTGRES_PASSWORD: '${DBPASS}'
      POSTGRES_USER: '${DBUSER}'